# Generated by Django 4.2.11 on 2024-10-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_modules', '0003_alter_moduleplugin_cmsplugin_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='modules',
        ),
    ]
